version: '3.7'

services:
  xmlfrontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: xml-frontend
    networks:
      - app-net-sql
    ports:
      - "3772:3772"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_BASE_URL: https://signxml.leonardogallo.co
      FORCE_COLOR: "1"
    labels:
      - traefik.enable=1
      - traefik.http.routers.xmlfrontend.rule=Host(`signxml.leonardogallo.co`)
      - traefik.http.routers.xmlfrontend.entrypoints=websecure
      - traefik.http.routers.xmlfrontend.priority=1
      - traefik.http.routers.xmlfrontend.tls.certresolver=letsencryptresolver
      - traefik.http.routers.xmlfrontend.service=xmlfrontend
      - traefik.http.services.xmlfrontend.loadbalancer.server.port=3772
    tty: true

  xmlbackend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: xml-backend
    networks:
      - app-net-sql
    ports:
      - "3771:3771"
    environment:
      NODE_ENV: production
      FORCE_COLOR: "1"
    volumes:
      - ./backend/output:/usr/src/app/output
      - ./backend/uploads:/usr/src/app/uploads
    labels:
      - traefik.enable=1
      - traefik.http.routers.xmlbackend.rule=Host(`signxml.leonardogallo.co`) && (PathPrefix(`/sign`) || PathPrefix(`/sign/download`))
      - traefik.http.routers.xmlbackend.priority=1
      - traefik.http.routers.xmlbackend.service=xmlbackend
      - traefik.http.routers.xmlbackend.entrypoints=websecure
      - traefik.http.routers.xmlbackend.tls.certresolver=letsencryptresolver
      - traefik.http.services.xmlbackend.loadbalancer.server.port=3771
    tty: true

networks:
  app-net-sql:
    name: app-net-sql
    external: true

volumes:
  backend-output:
  backend-uploads:
